### ISSUE TITLE
additionalfields.php

### ISSUE THREAD

**Issue by apopovski72** [c-softoy/whmcs-domain-module#2]
Hi

I see that in additionalfields.php there are missing arguments for the other mentioned tlds such .mk .  Is the file not updated or something else is the reason.

Thanks
Alex

**Comment by kasgel** [comment]
Hello,

The file was not updated, that was the reason.
Constantly updating the file and asking resellers to update their modules turned out to be non-sustainable. We are due to release version 1.2 of the module (currently available in kasgel/v1.2 branch) which fetches all additional fields from the NordName API dynamically. This way, we do not have to update the module each time we add a new TLD.
